### PR TITLE
Migrate to use async_forward_entry_setups

### PR DESCRIPTION
**Pull request by mmaarrkk02**
Replaces deprecated async_setup_platforms with async_forward_entry_setups

This PR is related to issue: #19

### CODE REVIEW

**Comment by kokoon** [comment]
This good to merge?

**Comment by LeeroyDing** [comment]
Looks trivial enough, should be safe to merge. Still need @aijayadams to have a look.

**Comment by TheTravelAddict** [comment]
as an FYI: This change fixed my issue.  I know others are also experiencing it.  Please merge

**Comment by sigio** [comment]
Pulling this fixes the integration now working in 2023.06 as well... please merge ;)

**Review by sigio — APPROVED** [review]

**Comment by Tokynet** [comment]
@aijayadams BUMP :)

**Comment by maxgoldberg** [comment]
Please merge!

**Comment by zx8** [comment]
Since this repo seems abandoned, I've migrated over to https://github.com/baihuqian/hass-blueair which also supports the newer AWS API.

**Comment by kokoon** [comment]
> Since this repo seems abandoned, I've migrated over to https://github.com/baihuqian/hass-blueair which also supports the newer AWS API.

This is not working for EU accounts, @mmaarrkk02 repo works.

**Comment by kokoon** [comment]
@mmaarrkk02 sorry to bother you, but your code stopped working with the last core update - now fails with
`ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)`

you think it's easily fixable?

**Comment by TheTravelAddict** [comment]
This does not necessarily sound like an error with the plug in specifically - That error message is indicative of your HASS server's SSL certificate being invalid. Usually because it expired or it was accessed not through the Domain Name in use by the cert - this happens to me when DuckDNS can't for whatever reason refresh the dyndns record.

**Comment by kokoon** [comment]
> This does not necessarily sound like an error with the plug in specifically - That error message is indicative of your HASS server's SSL certificate being invalid. Usually because it expired or it was accessed not through the Domain Name in use by the cert - this happens to me when DuckDNS can't for whatever reason refresh the dyndns record.

Thanks for your reply! I'm using HA Cloud (Nabu Casa) if that makes any difference. Also, I haven't had troubles with any of the other integrations and I have quite a few. Are you using the blueair integration?

**Pull request closed without merging**
